config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"
  get 'movies/ranking' => "movies#rank", as: "rank"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users

  get 'movies/search' => 'movies#search'

  post '/like/:comment_id' => 'likes#like', as: 'like'
  delete '/like/:comment_id' => 'likes#unlike', as: 'unlike'

  post "/relationships/:user_id" => "relationships#follow", as: "follow"
  delete "/relationships/:user_id" => "relationships#unfollow", as: "unfollow"

  resources :comments, only: [:create,:edit,:update,:destroy]
  resources :movies, only: [:show]
  resources :users, only: [:index,:show,:update]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create,:show,:index]
  # resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: "User"

    validates :user_id, presence: true
    validates :follow_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :set_variables

    # def create
    #   user = User.find(params[:follow_id])
    #   following = current_user.follow(user)
    #   if following.save
    #     flash[:success] = 'ユーザーをフォローしました'
    #     redirect_to user
    #   else
    #     flash.now[:alert] = 'ユーザーのフォローに失敗しました'
    #     redirect_to user
    #   end
    # end
  
    # def destroy
    #   user = User.find(params[:follow_id])
    #   following = current_user.unfollow(user)
    #   if following.destroy
    #     flash[:success] = 'ユーザーのフォローを解除しました'
    #     redirect_to user
    #   else
    #     flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
    #     redirect_to user
    #   end
    # end


    def follow
      follow = current_user.relationships.new(user_id: @user.id)
      follow.follow_id = params[:user_id].to_i
      follow.save
    end
    
    def unfollow
      follow = current_user.relationships.find_by(follow_id: @user.id)
      follow.destroy
    end
    
    private
    
    def set_variables
      @user = User.find(params[:user_id])
      @id_name = "#follow-link-#{@user.id}"
    end
    
  
    def set_user
    # binding.pry
      user = User.find(params[:follow_id])
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
    <div class="#follow-link-<%= @user.id %>">

        <% if current_user.relationships.find_by(follow_id: user.id) %>
            <%= link_to unfollow_path(user.id),method: :delete, remote: true do %>
                フォロー中
            <% end %>
        <% else %>
            <%= link_to follow_path(user.id),method: :post, remote: true do %>
                フォローする
            <% end %>
        <% end %>
    </div>
<% else %>
    <%= link_to new_user_session_path, "フォローする" %>
<% end %>

app/views/relationships/follow.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("relationships/follow_button", user: @user  )) %>');

app/views/relationships/follow_button.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("relationships/follow_button", user: @user  )) %>');

app/views/relationships/unfollow.jp.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("relationships/follow_button", user: @user  )) %>');