config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"
  get 'movies/ranking' => "movies#rank", as: "rank"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users

  get 'movies/search' => 'movies#search'

  post '/like/:comment_id' => 'likes#like', as: 'like'
  delete '/like/:comment_id' => 'likes#unlike', as: 'unlike'

  post "/relationships/:user_id" => "relationships#follow", as: "follow"
  delete "/relationships/:user_id" => "relationships#unfollow", as: "unfollow"

  resources :comments, only: [:create,:edit,:update,:destroy]
  resources :movies, only: [:show]
  resources :users, only: [:index,:show,:update]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create,:show,:index]
  # resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :comment, counter_cache: :likes_count
    belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(comment_id: @comment.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(comment_id: @comment.id)
    like.destroy
  end

  private

  def set_variables
    @comment = Comment.find(params[:comment_id])
    @id_name = "#like-link-#{@comment.id}"
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <div class="like-link" id="like-link-<%= comment.id %>">
    <% if current_user.likes.find_by(comment: comment.id) %>
      <%= link_to unlike_path(comment.id), method: :delete, remote: true do %>
          <div class = "iine__button">❤️<%= comment.likes.count %>　いいね</div>
      <% end %>
    <% else %>
      <%= link_to like_path(comment.id), method: :post, remote: true do %>
          <div class = "iine__button">♡️<%= comment.likes.count %>　いいね</div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div class="iine__button">♡️<%= comment.likes.count %>　いいね</div>
<% end %>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", comment: @comment  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", comment: @comment  )) %>');