config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"
  get 'movies/ranking' => "movies#rank", as: "rank"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users

  get 'movies/search' => 'movies#search'

  post '/like/:comment_id' => 'likes#like', as: 'like'
  delete '/like/:comment_id' => 'likes#unlike', as: 'unlike'

  post "/relationships/:user_id" => "relationships#follow", as: "follow"
  delete "/relationships/:user_id" => "relationships#unfollow", as: "unfollow"

  resources :comments, only: [:create,:edit,:update,:destroy]
  resources :movies, only: [:show]
  resources :users, only: [:index,:show,:update]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create,:show,:index]
  # resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :likes, dependent: :destroy
  has_many :like_comments, through: :likes, source: :comment

  has_many :relationships, dependent: :destroy
  # throughは中間テーブルはrelationshipsだよ、sourceはrelationshipsテーブルのfollow_idを参考にして、followingsモデルにアクセスしてね
  has_many :followings, through: :relationships, source: :follow
  # reverse_of_relationshipsは逆方向の記述、foreign_keyはrelaitonshipsテーブルにアクセスする時、follow_idを入口として来てね！
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  # foreign_keyは入り口、sourceは出口
  has_many :followers, through: :reverse_of_relationships, source: :user

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy



  def following?(other_user)
    self.followings.include?(other_user)
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #  super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up)
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:message]

  def show
    @user = User.find(params[:id])
    @follow = Relationship.where(user_id: @user.id)
    @follower = Relationship.where(follow_id: @user.id)
    likes = Like.where(user_id: @user.id)
    if likes[0].nil?
    else
      @like_comments = Comment.where(id: likes[0].comment_id)
    end
    if user_signed_in?
      @currentUserEntry=Entry.where(user_id: current_user.id)
      @userEntry=Entry.where(user_id: @user.id)
      if @user.id == current_user.id
      else
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    follow_list_id = []
    @comments = []
    if @user.relationships.nil? != true
      @user.relationships.each do |user|
        follow_list_id << user.follow_id
      end
      follow_list_id.each do |follow|
        @comments << Comment.where(user_id: follow).order(created_at: :desc)
      end
    end
  end

  def message
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(profile_params)
      flash[:notice] = "更新に成功しました！"
      redirect_to "/users/#{@user.id}"
    else
      flash[:notice] = "更新に失敗しました…"
      redirect_to "/users/#{@user.id}"
    end
  end


  private

  def profile_params
    params.require(:user).permit(:name,:gender,:profile,:movie1_title,:movie1_text,:movie2_title,:movie2_text,:movie3_title,:movie3_text)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="movie_index">
    <h3>フォローコメント</h3>
    <br>
    <% @comments.each do |comment| %>
        <div class="comment_list_li">
            <i class="fas fa-user fa-2x"></i>
            <% @user = @users.find(comment[0].user_id) %>
            <%= link_to @user.name, "/users/#{@user.id}" %>
            <h5 class="index_movie_title"><%= link_to comment[0].movie_title ,movie_path(comment[0].movie_id) %></h5>
            <h5><%= comment[0].title %></h5>
            <div class="comment_list_content"><%= simple_format(comment[0].content) %></div>
            <div class="comment_created_at"><%= comment[0].created_at.strftime("%Y-%m-%d %H:%M") %></div>
            <%= render partial: "/likes/like",locals: {comment: comment[0]}  %>
        </div>
    <hr>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="change_width">
<h2>ユーザー情報　<span class="user_flash"><%= flash[:notice] %></span></h2>
<h5>
<% if user_signed_in? %>
    <% if @user.id != current_user.id %>
        <%= render partial: "relationships/follow_button", locals: {user: @user} %>
    <% end %>
<% end %>

<div class="introduce_user_icon"><i class="fas fa-user fa-3x"></i></div>
<div class="introduce_user_id">性別：　<%= @user.gender %></div>
<div class="introduce_user_id">ID:　<%= @user.id %></div>
<div class="introduce_user_like_count">獲得いいね　<%= @user.likes.count %>いいね</div>
<div class="user_follower_parent">
    <div class="user_follower_child">
        <div class="user_follow_count">
            フォロー　<%= @user.relationships.count %><br>
        </div>
        <div class="user_follow_parent_modal">
            <div class="user_follow_modal">
                <div class="user_follower_list">
                <div class="align-right"><i class="fas fa-times fa-2x close_follow_modal"></i></div>
                    フォローリストID
                    <ul>
                        <% @follow.each do |follow| %>
                            <% @users = User.find(follow.follow_id) %>
                            <li><div class="user_follower_list_list"><%= link_to @users.name,user_path(follow.follow_id) %></div></li>
                        <% end %>
                    </ul><br><br>
                </div>
            </div>
        </div>
    </div>
    <div class="user_follower_child">
        <div class="user_follower_count">
            フォロワー　<%= @follower.count %>
        </div>
        <div class="user_follower_parent_modal">
            <div class="user_follower_modal">
                <div class="user_follower_list">
                    <div class="align-right"><i class="fas fa-times fa-2x close_follower_modal"></i></div>
                    フォロワーリスト
                    <ul>
                        <% @follower.each do |follower| %>
                            <div class="user_follower_list_list">
                                <li><%= link_to follower.user.name,user_path(follower.user_id) %></li>
                            </div>
                        <% end %>
                    <ul>
                        <br><br>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="introduce_user_name"><%= @user.name %>
    <%if  user_signed_in? %>
        <% if @user.id == current_user.id %>
            <i class="fas fa-pencil-alt profile_update"></i>
            　<span class="profile_introduction">プロフィールを更新</span>
        <% else %>
            <% if @isRoom == true %>
                <p><a href="/rooms/<%= @roomId %>">チャットへ</a>
            <% else %>
                <%= form_for @room do |f| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, :value=> @user.id %>
                  <% end %>
                  <%= f.submit "チャットを始める" %>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
</div>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavDropdown">
  <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" id="nav_profile_comment" href="#">コメント</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="nav_profile_profile" href="#">おすすめ映画</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="nav_profile_like" href="#">いいね</a>
    </li>
  </ul>
</div>
</nav>



<div class="user_profile_comment">
<% @user.comments.each do |comment| %>
    <div class="user_profile_comment_list">映画　<%= link_to comment.movie_title,movie_path(comment.movie_id) %></div>
    <h5 class="index_movie_title"><%= comment.title %></h5>
    <h6 class="user_profile_comment_list"><%= simple_format(comment.content) %></h6>
    <div class="comment_created_at"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></div>
    <% if user_signed_in? %>
        <% if current_user.id == comment.user.id %>
            <h6><%= link_to "削除", comment_path(comment.id), method: :delete %></h6>
        <% end %>
<% end %>
    <hr>
<% end %>

</div>
<div class="user_profile_profile">
    <div class="recomend_movie">
      <div class="recomend_movie_top"><h3>オススメしたい映画TOP3</h3></div>
        <div class="recomend_movie_content">
            <h4>
                <span id="recomend_movie_rank_1">1位</span>
                <%= @user.movie1_title %>
            </h4><br>
            <div class="recomend_movie_introduction">
                <%= simple_format(h(@user.movie1_text)) %>
            </div>
        </div>
        <hr>
        <div class="recomend_movie_content">
            <h4>
                <span id="recomend_movie_rank_2">2位</span>
                <%= @user.movie2_title %>
            </h4><br>
            <div class="recomend_movie_introduction">
                <%= simple_format(h(@user.movie2_text)) %>
            </div>
        </div>
        <hr>
        <div class="recomend_movie_content">
            <h4>
                <span id="recomend_movie_rank_3">3位</span>
                <%= @user.movie3_title %>
            </h4><br>
            <div class="recomend_movie_introduction">
                <%= simple_format(h(@user.movie3_text)) %>
            </div>
        </div>
        <hr>
    </div>
</div>
<div class="user_profile_like">
    <% if @like_comments.nil? != true  %>
        <% @like_comments.each do |comment| %>
            <h5 class="user_profile_comment_list"><%= link_to comment.user.name,user_path(comment.user_id) %></h5>
            <h5 class="user_profile_comment_list"><%= link_to comment.movie_title, movie_path(comment.movie_id) %></h5>
            <h5 class=""><%= comment.title %></h5>
            <h5 class="user_profile_comment_list"><%= comment.content %></h5>
            <hr>
        <% end %>
    <% end %>
</div>




<% if user_signed_in? %>
    <% if @user.id == current_user.id %>
    <div class="user_modal">
        <div class="user_modal_form">
            <div class="align-right"><i class="fas fa-times fa-2x close_modal"></i></div>
            <%= form_for @user  do |f| %>
                <div class="mypage_form">
                    <div><%= f.label :name, "ユーザー名" %></div>
                    <%= f.text_field :name %>
                </div>
                <br>

                <div class="mypage_form">
                    <div><%= f.label :gender ,"性別" %></div>
                    <%= f.select :gender, ["男性","女性","秘密"] %>
                </div>
                <br>

                <div class="mypage_form">
                    <div><%= f.label :profile, "自己紹介" %></div>
                    <%= f.text_area :profile %>
                </div>
                <hr>
                <div class="mypage_form">
                    <div><%= f.label :movie1_title , "1番の映画"%></div>
                    <%= f.text_field :movie1_title %>
                </div>
                <br>

                <div class="mypage_form">
                    <div><%= f.label :movie1_text ,"紹介文" %></div>
                    <%= f.text_area :movie1_text %>
                </div>
                <hr>
                <div class="mypage_form">
                    <div><%= f.label :movie2_title , "2番の映画"%></div>
                    <%= f.text_field :movie2_title %>
                </div>
                <br>

                <div class="mypage_form">
                    <div><%= f.label :movie2_text , "紹介文"%></div>
                    <%= f.text_area :movie2_text %>
                </div>
                <hr>
                <div class="mypage_form">
                    <div><%= f.label :movie3_title , "3番の映画"%></div>
                    <%= f.text_field :movie3_title %>
                </div>
                <br>

                <div class="mypage_form">
                    <div><%= f.label :movie3_text, "紹介文" %></div>
                    <%= f.text_area :movie3_text %>
                </div>
                <hr>
                <%= f.submit "プロフィール更新" %>
            <% end %>
            <br>
            </div>
        </div>
    <% end %>
<% end %>
</div>