config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"
  get 'movies/ranking' => "movies#rank", as: "rank"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users

  get 'movies/search' => 'movies#search'

  post '/like/:comment_id' => 'likes#like', as: 'like'
  delete '/like/:comment_id' => 'likes#unlike', as: 'unlike'

  post "/relationships/:user_id" => "relationships#follow", as: "follow"
  delete "/relationships/:user_id" => "relationships#unfollow", as: "unfollow"

  resources :comments, only: [:create,:edit,:update,:destroy]
  resources :movies, only: [:show]
  resources :users, only: [:index,:show,:update]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create,:show,:index]
  # resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :movie, optional: true
    belongs_to :user, optional: true 
    
    has_many :likes, dependent: :destroy
    has_many :liking_users, through: :likes, source: :user
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :comment, counter_cache: :likes_count
    belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/movie.rb
class Movie < ApplicationRecord
  include HTTParty  
  has_many :comments, dependent: :destroy
  



    # default_options.update(verify: false) # disable SSL verification(必要に応じて)
    default_params api_key: ENV['MOVIE_SECRET_KEY'], language: 'ja-JP' #共通パラメタ 

    
                
    format :json
    
    def self.top
      base_uri 'https://api.themoviedb.org/3/movie/popular'
      get("",query: {} )
    end

    # キーワードによる検索機能
    # https://developers.themoviedb.org/3/search/search-keywordsに参照
    def self.search term
      base_uri 'https://api.themoviedb.org/3/search/movie'
      get("", query: { query: term })# {}の中身はパラメタ
    end

    # def self.search term
    #   base_uri 'https://api.themoviedb.org/3'
    # end
    
    # 指定の映画の詳細情報を取得
    # https://developers.themoviedb.org/3/movies/get-movie-detailsに参照
    def self.details id
      base_uri "https://api.themoviedb.org/3/movie/#{id}"
      get("", query: { } ) #パラメタなし
    end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: "User"

    validates :user_id, presence: true
    validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :likes, dependent: :destroy
  has_many :like_comments, through: :likes, source: :comment

  has_many :relationships, dependent: :destroy
  # throughは中間テーブルはrelationshipsだよ、sourceはrelationshipsテーブルのfollow_idを参考にして、followingsモデルにアクセスしてね
  has_many :followings, through: :relationships, source: :follow
  # reverse_of_relationshipsは逆方向の記述、foreign_keyはrelaitonshipsテーブルにアクセスする時、follow_idを入口として来てね！
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  # foreign_keyは入り口、sourceは出口
  has_many :followers, through: :reverse_of_relationships, source: :user

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy



  def following?(other_user)
    self.followings.include?(other_user)
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(comment_id: @comment.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(comment_id: @comment.id)
    like.destroy
  end

  private

  def set_variables
    @comment = Comment.find(params[:comment_id])
    @id_name = "#like-link-#{@comment.id}"
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!
    def create
      @room = Room.create
      @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
      @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
      redirect_to "/rooms/#{@room.id}"
    end
  
    def show
      @room = Room.find(params[:id])
      if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
        @messages = @room.messages
        @message = Message.new
        @entries = @room.entries
      else
        redirect_back(fallback_location: root_path)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:message]

  def show
    @user = User.find(params[:id])
    @follow = Relationship.where(user_id: @user.id)
    @follower = Relationship.where(follow_id: @user.id)
    likes = Like.where(user_id: @user.id)
    if likes[0].nil?
    else
      @like_comments = Comment.where(id: likes[0].comment_id)
    end
    if user_signed_in?
      @currentUserEntry=Entry.where(user_id: current_user.id)
      @userEntry=Entry.where(user_id: @user.id)
      if @user.id == current_user.id
      else
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    follow_list_id = []
    @comments = []
    if @user.relationships.nil? != true
      @user.relationships.each do |user|
        follow_list_id << user.follow_id
      end
      follow_list_id.each do |follow|
        @comments << Comment.where(user_id: follow).order(created_at: :desc)
      end
    end
  end

  def message
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(profile_params)
      flash[:notice] = "更新に成功しました！"
      redirect_to "/users/#{@user.id}"
    else
      flash[:notice] = "更新に失敗しました…"
      redirect_to "/users/#{@user.id}"
    end
  end


  private

  def profile_params
    params.require(:user).permit(:name,:gender,:profile,:movie1_title,:movie1_text,:movie2_title,:movie2_text,:movie3_title,:movie3_text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>映画の子</title>

    <%= csrf_meta_tags %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>
  <header>
      <ul class="nav nav-pills">
        <div class="header_logo"></div>
        <h3 class="header_title">映画の子</h3>
        <div class="header_search">
          <li>
            <%= form_tag(movies_search_path, method: :get) do %>
              <%= search_field_tag :looking_for, nil, placeholder: '映画を検索' %>
              <%= submit_tag '検索' %>
            <% end %>
          </li>
        </div>



        <div class="nav_access">
              <li class="nav_list"><%= link_to "トップ",root_path ,class: "nav_list" %></li>
              <li class="nav_list"><%= link_to "ランキング", rank_path ,class: "nav_list" %></li>
        </div>
        <% if user_signed_in? %>
          <select onChange="top.location.href=value" name="user_drop" class="user_drop">
            <option>ユーザー</option>
            <option value="/users">フォローコメント</option>
            <option value="/users/<%=current_user.id%>">プロフィール</option>
            <option value="/users/edit">アカウント設定</option>
          </select>
        <% end %>


        <%if user_signed_in? %>
          <i class="fas fa-sign-out-alt sign_out_icon fa-2x white"></i>
          <li class="active"><%= link_to "ログアウト", destroy_user_session_path, {class: "btn btn_sign_out",method: :delete} %></li>

        <% else %>
          <li class="header_list_log_in"><%= link_to "ログイン", new_user_session_path, class: "btn btn_log_in" %></li>
          <li><%= link_to "新規登録", new_user_registration_path, class: "btn btn_sign_in" %></li>
        <% end %>
      </ul>
    
  </header>



  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-1">
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
      <div class="col-md-1">
      </div>
	    <footer>
			
      </footer>

      </div>
    </div>
  </div>
  </body>
</html>